---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd
    augeas_core:
      repo: https://github.com/simp/pupmod-puppetlabs-augeas_core.git
      puppet_version: ">= 6.0.0"
    augeasproviders_core: https://github.com/hercules-team/augeasproviders_core
    augeasproviders_grub: https://github.com/hercules-team/augeasproviders_grub
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup
    concat:
      # master is beyond 4.1.1, but has breaking changes to
      # how fragments are ordered (MODULES-6625)
      repo: https://github.com/simp/puppetlabs-concat
      ref: 4.1.1
    iptables: https://github.com/simp/pupmod-simp-iptables
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    pki: https://github.com/simp/pupmod-simp-pki
    selinux_core: https://github.com/puppetlabs/puppetlabs-selinux_core
    simp_options: https://github.com/simp/pupmod-simp-simp_options
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    stunnel: https://github.com/simp/pupmod-simp-stunnel
    systemd: https://github.com/simp/puppet-systemd
    tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers
  symlinks:
    rsyslog: "#{source_dir}"
